Limited PhoneNumber Country code and Phonenumber Length,
afet-yonetim-sistemi/ays-be pull request #114
Opened 2023-07-04 13:29 UTC by ilkerCelimli

# PULL REQUEST TEMPLATE

## Description

Please provide a brief description of the changes made in this pull request.

## Related Issue

If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.

## Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Feature/issue-number/feature-description: [Feature Description]
- Refactor/issue-number/issue-description: [Issue Description]
- ...

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [ ] I have tested my changes locally and they are working as expected.
- [ ] The code is formatted according to the project's coding guidelines and style.
- [ ] Necessary documentation has been added or existing documentation has been updated.
- [ ] Relevant unit tests have been written and included.
- [ ] Relevant integration tests have been written and included.
- [ ] The code has been reviewed to ensure its quality.
- [ ] The code does not contain any issues flagged by SonarLint.
- [ ] Default reviewers have been assigned to this pull request.
- [ ] Assignees have been added if necessary.
- [ ] Labels have been applied if necessary.
- [ ] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-07-04 13:31 UTC, ilkerCelimli commented
@agitrubard , @Rapter1990  @skayikci 

Mecburen Veritabanında değişiklik yapmak zorunda kaldım koaly bir şekilde işin halledilebilmesi için,

2023-07-04 15:44 UTC, ilkerCelimli commented
LineNumber kısmı 11 hanelide hata vermeye başladığı için, Onu String, ve veri tabanı kısmında Varchar(10) yaptım, 
Country code kısmı zaten düzgün çalışıyor onu ellemeye gerek yok, 
@skayikci 
@agitrubard 
@Rapter1990  bi kontrol eder misiniz eksik var mı ?

2023-07-04 16:02 UTC, agitrubard commented
@ilkerCelimli branch standartlarına uyması açısından bundan sonraki geliştirmelerde branch açtığın zaman aşağıdaki branch standartlarına uygun olacak şekilde açabilir misin?

---

**Naming Conventions of Branchs**
- `bugfix/{issue-number}/{optional-description}`
  - Ex: `bugfix/0/authentication-flow` or `bugfix/0`
- `feature/{issue-number}_{optional-description}`
  - Ex: `feature/0/admin-register-flow` or `feature/0`
- `refactor/{issue-number}_{optional-description}`
  - Ex: `refactor/0/tests-classes` or `refactor/0`
- `hotfix/{issue-number}_{optional-description}`
  - Ex: `hotfix/0/authorization-flow` or `hotfix/0`
  
---
  
**Naming Conventions of Pull Requests**
- `#{issue-number} | {header-for-summary-of-development}`
  - Ex: `#0 | Authentication/Authorization Flows Has Been Created`

---

> Bu kısımlar `README.md` dosyasında yazmıyordu sanırım, ekliyor olacağım.

2023-07-04 16:06 UTC, agitrubard requested changes
Benzer geliştirmeleri `AdminUserEntity` içerisinde de yapmalıyız. Ek olarak Admin Kayıt ve Kullanıcı Kayıt akışındaki requestlerde bulunan `AysPhoneNumber` objesi içerisinde de bu kısıtlamaları yapmalıyız. Fakat burada neden String kullanma ihtiyacımız olduğunu tam olarak anlayamadım. `@Range` anotasyonu ile kısıtlayabiliyoruz, veritabanında da `INTEGER(10)` olarak uzunluğunu belirtebiliyoruz.

2023-07-04 16:06 UTC, agitrubard commented on src/main/resources/db/changelog/changes/1-ays-ddl.xml
> +            <column name="COUNTRY_CODE" type="MEDIUMINT">
Eğer uygulama içerisinde `String` tipinde tutuyorsak burada da `VARCHAR` tipinde tutabiliriz.

2023-07-04 16:06 UTC, agitrubard commented on src/main/resources/db/changelog/changes/1-ays-ddl.xml
> +            <column name="COUNTRY_CODE" type="MEDIUMINT">
Eğer uygulama içerisinde `String` tipinde tutuyorsak burada da `VARCHAR` tipinde tutabiliriz.

2023-07-04 16:06 UTC, agitrubard commented on src/main/java/com/ays/user/model/entity/UserEntity.java
>      private Long countryCode;
`countryCode` alanının da veri tipi de standart olması açısından `String` olarak değişmeli

2023-07-04 17:01 UTC, ilkerCelimli commented
11 haneli bir sayı vermeye çalıştığımda number is very big diyip parse hatası veriyor. O yüzden string kullanmak daha iyi diye düşündüm

2023-07-04 17:17 UTC, ilkerCelimli commented
Veritabanı tarafını bilemem, MYSQL pek kullanmadım, 

String kullanılma sebebi, Her bir string'in 1 byte olması ve varchar(10) durumunda bellekte sadece 10 byte alan açılması,bu da performans artışı sağlar, 

BIGINT 2^63 tü sanırsam kadar default olarak alan açtığı için, buda veri boyutunu büyük oranda arttırır.

Bir başka String kullanma sebebi ise, telefon no'ları için konuşmak gerekirse String üzerinde işlem yapması daha basit olacağı için,

@Range anotasyonu için konuşmak gerekirse,Açıkcası hiç kullanmamıştım onu , o yüzden yorum yapamıcam,

2023-07-05 15:50 UTC, agitrubard commented
@ilkerCelimli ek olarak aşağıdaki yorum içerisinde yazdığım standartları gözden geçirebilir misin?

https://github.com/afet-yonetim-sistemi/ays-be/pull/114#issuecomment-1620489019

2023-07-05 16:06 UTC, ilkerCelimli commented
> @ilkerCelimli ek olarak aşağıdaki yorum içerisinde yazdığım standartları gözden geçirebilir misin?
> 
> [#114 (comment)](https://github.com/afet-yonetim-sistemi/ays-be/pull/114#issuecomment-1620489019)

Standartlara uygun olarak olarak değiştirdim PR ismini, Tabi müsait ikimizde müsait olduğumuzda bakalım,Ama şuan bir sıkıntı olmaması gerek.

2023-07-07 06:09 UTC, ilkerCelimli commented
@agitrubard  Gerekli düzenlemeyi yaptım, Bi kontrol edebilirseniz sevinirim.

2023-07-07 06:25 UTC, agitrubard requested changes

2023-07-07 06:25 UTC, agitrubard commented on src/test/java/com/ays/common/model/AysPhoneNumberBuilder.java
> +    public AysPhoneNumberBuilder withLineNumber(String lineNumber) {
Bu sınıf içerisindeki geliştirmelere ihtiyaç kalmadığı için geri alabilir miyiz?

2023-07-07 06:25 UTC, agitrubard commented on src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImplTest.java
>          Mockito.verify(adminUserRegisterVerificationRepository, Mockito.times(1))
Bu sınıf içerisindeki geliştirmelere ihtiyaç kalmadığı için geri alabilir miyiz?

2023-07-07 06:25 UTC, agitrubard commented on src/main/java/com/ays/common/model/AysPhoneNumber.java
>      /**
`min` değeri tanımlama ihtiyacımız bulunmuyor, sadece maksimum değer versek yeterli olur diye düşünüyorum

2023-07-07 06:25 UTC, agitrubard commented on src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImpl.java
>          log.trace("Admin User Register Request checked successfully!");
Bu sınıf içerisindeki geliştirmelere ihtiyaç kalmadığı için geri alabilir miyiz?

2023-07-07 06:25 UTC, agitrubard commented on src/main/java/com/ays/admin_user/repository/AdminUserRepository.java
>  }
Bu sınıf içerisindeki geliştirmelere ihtiyaç kalmadığı için geri alabilir miyiz?

2023-07-07 16:10 UTC, moaydogdu commented
CountryCode ve LineNumber alanları için bazı uyumsuzluklar mevcut.

- LineNumber kısmı 13 haneye kadar gidebiliyor(China). 
- CountryCode kısmı 7 haneye kadar gidebiliyor (Christmas Island, Cocos (Keeling) Islands). 

Kaynaklar: 
- [International Calling Codes](https://www.internationalcitizens.com/international-calling-codes/)
- [Line Number Lengths](https://worldpopulationreview.com/country-rankings/phone-number-length-by-country)
- [Country Codes](https://countrycode.org/)

2023-07-08 16:08 UTC, ilkerCelimli commented
@agitrubard değiliklikleri yaptım, Ama 13 'e 7 yapsak daha iyi olucak sanırsam

2023-07-10 20:15 UTC, agitrubard requested changes

2023-07-10 20:15 UTC, agitrubard commented on src/main/java/com/ays/admin_user/repository/AdminUserRepository.java
>  }
Burada primitive type kullanmıyor olmamız daha doğru olur, daha önceden olduğu gibi Object kullanalım

2023-07-10 20:16 UTC, agitrubard commented
@ilkerCelimli Selamlar,
Pull request başlığını aşağıdaki standarda uyacak şekilde güncelleyebilir miyiz?
  
**Naming Conventions of Pull Requests**
- `#{issue-number} | {header-for-summary-of-development}`
  - Ex: `#0 | Authentication/Authorization Flows Has Been Created`

2023-07-10 20:18 UTC, agitrubard commented
> @agitrubard değiliklikleri yaptım, Ama 13 'e 7 yapsak daha iyi olucak sanırsam

@ilkerCelimli bu konuda standart bu şekildeyse böyle güncelleyebiliriz, fakat çalışmama gibi bir problem ile karşılaşmamak için detaylı testlerini yapmamız sağlıklı olur. Unit test'ten bahsetmiyorum, bunun dışındaki testlerden bahsediyorum. Ek olarak uzunluk ile ilgili de bir unit test case yazarak bu geliştirmeyi en doğru şekilde cover etmiş oluruz.

2023-07-11 19:11 UTC, agitrubard approved these changes

2023-07-11 19:12 UTC, agitrubard commented
@ilkerCelimli eline sağlık, `Long` veri tipi ile ilgili test yaptığımda çok problemler çıkıyordu, testlerle beraber düzelttim. Diğer arkadaşlar da kontrol ederse mergeleyebiliriz.

2023-07-12 11:57 UTC, Rapter1990 approved these changes
LGTM!

2023-07-12 15:15 UTC, merged