Refactor default createdUser and updatedUser values
afet-yonetim-sistemi/ays-be pull request #122
Opened 2023-07-09 18:23 UTC by Rapter1990

# PULL REQUEST TEMPLATE

## Description

Refactor default createdUser and updatedUser value

## Related Issue

In the process of registering admin, createdUser and updatedUser values cannot be set as the JWT token cannot be valid. 

## Proposed Changes

Revise the process to determine if the JWT token is valid for registering the admin.

- refactor/116determine-default-createduser-and-updateduser-value

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [x] I have tested my changes locally and they are working as expected.
- [x] The code is formatted according to the project's coding guidelines and style.
- [x] Necessary documentation has been added or existing documentation has been updated.
- [x] Relevant unit tests have been written and included.
- [x] Relevant integration tests have been written and included.
- [x] The code has been reviewed to ensure its quality.
- [x] The code does not contain any issues flagged by SonarLint.
- [x] Default reviewers have been assigned to this pull request.
- [x] Assignees have been added if necessary.
- [x] Labels have been applied if necessary.
- [x] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-07-11 19:25 UTC, agitrubard requested changes

2023-07-11 19:25 UTC, agitrubard commented on src/main/java/com/ays/common/model/entity/BaseEntity.java
>  }
Aşağıdaki şekilde ilerleyebiliriz, hem daha okunaklı olur, hem de tek yerde çözmüş oluruz.

```
@PrePersist
public void prePersist() {
   this.createdUser = Optional.ofNullable(SecurityContextHolder.getContext().getAuthentication())
            .map(Authentication::getPrincipal)
            .map(Jwt.class::cast)
            .map(jwt -> jwt.getClaim(AysTokenClaims.USERNAME.getValue()).toString())
            .orElse("AYS");
   this.createdAt = LocalDateTime.now();
}

...

@PreUpdate
public void preUpdate() {
   this.updatedUser = Optional.ofNullable(SecurityContextHolder.getContext().getAuthentication())
            .map(Authentication::getPrincipal)
            .map(Jwt.class::cast)
            .map(jwt -> jwt.getClaim(AysTokenClaims.USERNAME.getValue()).toString())
            .orElse("AYS");
   this.updatedAt = LocalDateTime.now();
}
```

2023-07-12 15:25 UTC, agitrubard approved these changes

2023-07-13 07:27 UTC, skayikci approved these changes

2023-07-13 07:27 UTC, moaydogdu approved these changes
LGTM!

2023-07-13 07:42 UTC, merged