#90 | Implementation of checking whether user has assignment for update user support status endpoint
afet-yonetim-sistemi/ays-be pull request #178
Opened 2023-09-17 15:08 UTC by ibrahimdenizz

# PULL REQUEST TEMPLATE

## Description

Implementation of checking whether user has assignment for update user support status endpoint.
When user update user support status to statuses that specified in issue, It checks whether user has assignment.
If user has assignment, it throws exception and doesn't update support status.

## Related Issue

#90 

## Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [X] I have tested my changes locally and they are working as expected.
- [X] The code is formatted according to the project's coding guidelines and style.
- [X] Necessary documentation has been added or existing documentation has been updated.
- [X] Relevant unit tests have been written and included.
- [X] Relevant integration tests have been written and included.
- [X] The code has been reviewed to ensure its quality.
- [X] The code does not contain any issues flagged by SonarLint.
- [X] Default reviewers have been assigned to this pull request.
- [X] Assignees have been added if necessary.
- [X] Labels have been applied if necessary.
- [x] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-09-18 07:22 UTC, agitrubard requested changes
Testleri geliştirmeler tamamlandıktan sonra tekrardan review ediyor olacam

2023-09-18 07:22 UTC, agitrubard commented on src/main/java/com/ays/user/service/impl/UserSelfServiceImpl.java
> +        }
Bu kısımda user'ı bulmaktan ziyade, şöyle bir logic yapmalıyız;
- eğer ki bu user'ın assignment'ı varsa
   - Assignment'ı varsa güncelleyebilececeği statülere göre bir kontrol yapılıp uygun exception fırlatılmalı
   - Assignment'ı yoksa standart bir şekilde güncelleyebileceği statüleri yine güncelleyebilmeli yani var olan akış değiştirilmemeli

2023-09-18 07:22 UTC, agitrubard commented on src/main/java/com/ays/user/util/exception/AysUserAlreadyHasAssignmentException.java
> +}
Java DOC'ların düzeltilmesi gerekiyor, sanırım güncellenmemiş

2023-09-18 07:22 UTC, agitrubard commented on src/test/java/com/ays/assignment/model/entity/AssignmentEntityBuilder.java
> +
Burada belki yapacağımız düzenlemeyle birlikte buradaki eklemlere ihtiyaç kalmayabilir

2023-09-18 16:35 UTC, ibrahimdenizz commented on src/main/java/com/ays/user/model/dto/request/UserSupportStatusUpdateRequest.java
> +    public boolean isSupportStatusChecked() {
Güncellendi!

2023-09-18 16:35 UTC, ibrahimdenizz commented on src/main/java/com/ays/user/util/exception/AysUserAlreadyHasAssignmentException.java
> +}
Güncellendi!

2023-09-18 19:48 UTC, ibrahimdenizz commented on src/main/java/com/ays/user/service/impl/UserSelfServiceImpl.java
> +        }
Güncellendi!

2023-09-18 19:48 UTC, ibrahimdenizz commented on src/test/java/com/ays/assignment/model/entity/AssignmentEntityBuilder.java
> +
Güncellendi!

2023-09-19 05:30 UTC, agitrubard approved these changes

2023-09-19 08:25 UTC, anilhazar approved these changes

2023-09-19 21:17 UTC, merged