#171 | Added global exception handler for JSON parsing error
afet-yonetim-sistemi/ays-be pull request #181
Opened 2023-09-19 16:53 UTC by ibrahimdenizz

# PULL REQUEST TEMPLATE

## Description

I added global exception handler for JSON parsing error.  

## Related Issue

#171 

## Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [X] I have tested my changes locally and they are working as expected.
- [X] The code is formatted according to the project's coding guidelines and style.
- [X] Necessary documentation has been added or existing documentation has been updated.
- [X] Relevant unit tests have been written and included.
- [X] Relevant integration tests have been written and included.
- [X] The code has been reviewed to ensure its quality.
- [X] The code does not contain any issues flagged by SonarLint.
- [X] Default reviewers have been assigned to this pull request.
- [X] Assignees have been added if necessary.
- [X] Labels have been applied if necessary.
- [X] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-09-19 21:19 UTC, agitrubard requested changes

2023-09-19 21:19 UTC, agitrubard commented on src/main/java/com/ays/common/util/exception/handler/GlobalExceptionHandler.java
> +                .build();
Buraya `.httpStatus(HttpStatus.BAD_REQUEST)` kısmını da ekleyebilir miyiz?

2023-09-20 18:35 UTC, ibrahimdenizz commented on src/main/java/com/ays/common/util/exception/handler/GlobalExceptionHandler.java
> +                .build();
Güncellendi!

2023-09-21 05:20 UTC, agitrubard approved these changes

2023-09-21 06:57 UTC, Rapter1990 approved these changes

2023-09-21 08:02 UTC, anilhazar approved these changes

2023-09-21 12:53 UTC, moaydogdu approved these changes
LGTM!

2023-09-21 12:56 UTC, AhmetAksunger approved these changes

2023-09-21 15:26 UTC, merged