#180 | Resolved The User Assignment Existence Bug in Assignment Search Flow
afet-yonetim-sistemi/ays-be pull request #184
Opened 2023-09-21 18:16 UTC by anilhazar

# PULL REQUEST TEMPLATE

## Description

Implemented User's Assigment's Existence Check in Assignment Search Flow.

## Related Issue

#180 

## Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [X] I have tested my changes locally and they are working as expected.
- [X] The code is formatted according to the project's coding guidelines and style.
- [X] Necessary documentation has been added or existing documentation has been updated.
- [X] Relevant unit tests have been written and included.
- [X] Relevant integration tests have been written and included.
- [X] The code has been reviewed to ensure its quality.
- [X] The code does not contain any issues flagged by SonarLint.
- [X] Default reviewers have been assigned to this pull request.
- [X] Assignees have been added if necessary.
- [X] Labels have been applied if necessary.
- [X] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-09-21 18:39 UTC, moaydogdu requested changes

2023-09-21 18:39 UTC, moaydogdu commented on src/main/java/com/ays/assignment/util/exception/AysAssignmentUserAlreadyAssigned.java
> +        super("USER ALREADY HAS AN ASSIGNMENT! userId:" + userId);
Statik bir default mesaj halinde tanımlanabilir.

2023-09-21 18:49 UTC, moaydogdu approved these changes
LGTM!

2023-09-21 19:02 UTC, ibrahimdenizz requested changes

2023-09-21 19:13 UTC, AhmetAksunger commented on src/test/java/com/ays/assignment/service/impl/AssignmentSearchServiceImplTest.java
> +                .findNearestAvailableAssignment(Mockito.any(Point.class), Mockito.anyString());
Yeni committe çözüldü.

2023-09-21 19:13 UTC, AhmetAksunger commented on src/main/java/com/ays/assignment/util/exception/AysAssignmentUserAlreadyAssigned.java
> +
Yeni committe çözüldü.

2023-09-21 19:13 UTC, AhmetAksunger commented on src/main/java/com/ays/assignment/util/exception/AysAssignmentUserAlreadyAssigned.java
> +    private static final long serialVersionUID = -3240549605152804148L;
Yeni committe çözüldü.

2023-09-21 19:15 UTC, ibrahimdenizz submitted a review, later dismissed

2023-09-22 07:12 UTC, agitrubard requested changes

2023-09-22 07:12 UTC, agitrubard commented on src/main/java/com/ays/assignment/service/impl/AssignmentSearchServiceImpl.java
> +        }
Burada assignment'ın statü kontrolü de yapılmalı, eğer statüsü `COMPLETED` değil ise buradaki hata fırlatılmalı. Issue içerisine bu detayı yazmamışım, issue içerisini de güncelledim ✅

2023-09-22 12:29 UTC, AhmetAksunger commented on src/main/java/com/ays/assignment/service/impl/AssignmentSearchServiceImpl.java
> +        }
Hallettim.

2023-09-22 13:31 UTC, ibrahimdenizz submitted a review, later dismissed

2023-09-22 17:05 UTC, agitrubard requested changes

2023-09-22 17:05 UTC, agitrubard commented on src/main/java/com/ays/assignment/service/impl/AssignmentSearchServiceImpl.java
> +        }
Buna birlikte bakalım @AhmetAksunger @anilhazar

2023-09-23 07:31 UTC, agitrubard approved these changes

2023-09-23 08:43 UTC, ibrahimdenizz approved these changes

2023-09-23 10:27 UTC, merged