#198 | Add Custom Banner
afet-yonetim-sistemi/ays-be pull request #199
Opened 2023-09-24 16:04 UTC by AhmetAksunger

# PULL REQUEST TEMPLATE

## Description
Created a custom banner for the logs

## Related Issue
#198 
## Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [X] I have tested my changes locally and they are working as expected.
- [X] The code is formatted according to the project's coding guidelines and style.
- [X] Necessary documentation has been added or existing documentation has been updated.
- [X] Relevant unit tests have been written and included.
- [X] Relevant integration tests have been written and included.
- [X] The code has been reviewed to ensure its quality.
- [X] The code does not contain any issues flagged by SonarLint.
- [X] Default reviewers have been assigned to this pull request.
- [X] Assignees have been added if necessary.
- [X] Labels have been applied if necessary.
- [X] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-09-24 16:07 UTC, AhmetAksunger commented
Sonuç şöyle, harflerin renkleri ayrı ayrı değiştirilebilir ve alt taraftaki bilgiler düzenlenebilir. Review atarsanız bakarım
![Screenshot from 2023-09-24 19-02-12](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/fcf2c3bb-668e-45b5-af95-977ad3ca73d6)

2023-09-25 12:03 UTC, agitrubard commented
> Sonuç şöyle, harflerin renkleri ayrı ayrı değiştirilebilir ve alt taraftaki bilgiler düzenlenebilir. Review atarsanız bakarım
> ![Screenshot from 2023-09-24 21-28-17](https://user-images.githubusercontent.com/116587797/270184478-37a4a29b-f0cf-4265-a3e1-7be90430320f.png)

Biraz elden geçirdim, bir de böyle kontrol edebilirsiniz @afet-yonetim-sistemi/back-end 
```
${AnsiColor.GREEN}     ___${AnsiColor.BLUE}  ____    ____${AnsiColor.YELLOW}  _______.
${AnsiColor.GREEN}    /   \${AnsiColor.BLUE} \   \  /   /${AnsiColor.YELLOW} /       |
${AnsiColor.GREEN}   /  ^  \${AnsiColor.BLUE} \   \/   /${AnsiColor.YELLOW} |   (----`
${AnsiColor.GREEN}  /  /_\  \${AnsiColor.BLUE} \_    _/${AnsiColor.YELLOW}   \   \
${AnsiColor.GREEN} /  _____  \${AnsiColor.BLUE}  |  |${AnsiColor.YELLOW} .----)   |
${AnsiColor.GREEN}/__/     \__\${AnsiColor.BLUE} |__|${AnsiColor.YELLOW} |_______/${AnsiColor.BRIGHT_WHITE}〔v${info.application.version}〕
:: AYS | Afet Yönetim Sistemi ::
${AnsiColor.DEFAULT}
```
![image](https://github.com/afet-yonetim-sistemi/ays-be/assets/61833677/48b0dabd-c078-4e22-b89a-95085dbacd64)

2023-09-25 12:04 UTC, agitrubard requested changes
Ben de bir şeyler yaptım, ona göre en son değerlendirelim

2023-09-25 14:15 UTC, agitrubard approved these changes

2023-09-25 19:53 UTC, moaydogdu approved these changes

2023-09-25 20:10 UTC, anilhazar approved these changes

2023-09-25 20:44 UTC, merged