#207 | Add a Null Check to `PhoneNumberValidator`
afet-yonetim-sistemi/ays-be pull request #209
Opened 2023-09-26 11:43 UTC by AhmetAksunger

# PULL REQUEST TEMPLATE

## Description

Added a null check to `PhoneNumberValidator` to prevent getting 500 HTTP error when there are missing attributes.

## Related Issue

#207 

## Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

## Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

## Checklist

Please check the following before submitting your pull request:

- [x] I have tested my changes locally and they are working as expected.
- [x] The code is formatted according to the project's coding guidelines and style.
- [x] Necessary documentation has been added or existing documentation has been updated.
- [x] Relevant unit tests have been written and included.
- [x] Relevant integration tests have been written and included.
- [x] The code has been reviewed to ensure its quality.
- [x] The code does not contain any issues flagged by SonarLint.
- [x] Default reviewers have been assigned to this pull request.
- [x] Assignees have been added if necessary.
- [x] Labels have been applied if necessary.
- [x] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

## Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-09-26 16:10 UTC, agitrubard requested changes
Bu geliştirmeyi test ettik mi? Artık 500 vermiyor mu? Ne gibi bir hata dönüyoruz?

2023-09-26 18:01 UTC, AhmetAksunger commented
> Bu geliştirmeyi test ettik mi? Artık 500 vermiyor mu? Ne gibi bir hata dönüyoruz?

Evet, artık AysPhoneNumber objesinde bulunan NotNull anotasyonuna takılıp 400 HTTP kodlu validation hatası veriyor. 

Önceden 500 Internal Error vermesinin sebebi, NotNull anotasyonundan PhoneNumber anotasyonuna gidip orada Null Pointer hatası almamızdı.
PhoneNumber anotasyonunda artık null durumlarda true dönüyoruz, kalan işlemi NotNull anotasyonuna bırakıyoruz.

2023-09-27 14:06 UTC, agitrubard commented
> > Bu geliştirmeyi test ettik mi? Artık 500 vermiyor mu? Ne gibi bir hata dönüyoruz?
> 
> Evet, artık AysPhoneNumber objesinde bulunan NotNull anotasyonuna takılıp 400 HTTP kodlu validation hatası veriyor.
> 
> Önceden 500 Internal Error vermesinin sebebi, NotNull anotasyonundan önce PhoneNumber anotasyonuna gidip orada Null Pointer hatası almamızdı. PhoneNumber anotasyonunda artık null durumlarda true dönüyoruz, kalan işlemi NotNull anotasyonuna bırakıyoruz.
> 
> @agitrubard

Süper eline sağlık 🙌🏼

2023-09-27 14:06 UTC, agitrubard approved these changes

2023-09-28 14:58 UTC, anilhazar approved these changes

2023-09-28 15:25 UTC, merged