Create the Main Structure for Admin Register Application Flow
afet-yonetim-sistemi/ays-be pull request #250
Opened 2023-11-12 22:24 UTC by AhmetAksunger

### Description

Created the main classes for the admin register application flow. The main reason for this pull request to be created is to avoid possible conflicts while developing the register application flow in parallel with other developers.

### Related Issue

There's no direct related issue with this pull request. 

### Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

### Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

### Checklist

Please check the following before submitting your pull request:

- [x] I have tested my changes locally and they are working as expected.
- [x] The code is formatted according to the project's coding guidelines and style.
- [x] Necessary documentation has been added or existing documentation has been updated.
- [x] Relevant unit tests have been written and included.
- [x] Relevant integration tests have been written and included.
- [x] The code has been reviewed to ensure its quality.
- [x] The code does not contain any issues flagged by SonarLint.
- [x] Default reviewers have been assigned to this pull request.
- [x] Assignees have been added if necessary.
- [x] Labels have been applied if necessary.
- [x] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

### Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-11-13 16:48 UTC, agitrubard requested changes
Oluşturulan sınıflarda herhangi bir problem yok, eline sağlık 🙌🏼 

Ortak kullanılacak başka sınıflar var mı? Entity olabilir, domain model olabilir

2023-11-13 17:01 UTC, AhmetAksunger commented
> Oluşturulan sınıflarda herhangi bir problem yok, eline sağlık 🙌🏼
> 
> Ortak kullanılacak başka sınıflar var mı? Entity olabilir, domain model olabilir

Entity zaten oluşturulmuş. Ekstradan domain modeli ve entity -> domain model mapper sınıflarını oluşturdum.

2023-11-13 17:29 UTC, agitrubard submitted a review, later dismissed

2023-11-15 15:56 UTC, ibrahimdenizz approved these changes
LGTM!

2023-11-15 15:59 UTC, ibrahimdenizz requested changes

2023-11-15 15:59 UTC, ibrahimdenizz commented on src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java
> +public class AdminUserRegisterApplicationServiceImplTest extends AbstractUnitTest {
Mock repository ve servisi ekliyebiliriz

2023-11-15 15:59 UTC, ibrahimdenizz commented on src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
> +public class AdminUserRegisterApplicationControllerTest extends AbstractRestControllerTest {
Mock servisi ekliyebiliriz.

2023-11-15 16:10 UTC, agitrubard commented
@AhmetAksunger Selamlar,
@ibrahimdenizz'in yazdığı yorumlara bakabilir misin? Bu geliştirmeyi mergeleyelim, diğer geliştirmelerin önü açılsın

2023-11-15 16:57 UTC, anilhazar approved these changes

2023-11-15 20:34 UTC, AhmetAksunger commented on src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java
> +public class AdminUserRegisterApplicationServiceImplTest extends AbstractUnitTest {
Ekledim.

2023-11-15 20:34 UTC, AhmetAksunger commented on src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
> +public class AdminUserRegisterApplicationControllerTest extends AbstractRestControllerTest {
Ekledim.

2023-11-16 09:38 UTC, ibrahimdenizz approved these changes

2023-11-17 15:41 UTC, agitrubard approved these changes

2023-11-17 15:41 UTC, merged