#238 | Implement the Admin User Registration Application Detail Endpoint
afet-yonetim-sistemi/ays-be pull request #261
Opened 2023-11-25 17:22 UTC by ibrahimdenizz

### Description

I have implemented detail endpoint for the admin user registration application

### Related Issue

#238 

### Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

### Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

### Checklist

Please check the following before submitting your pull request:

- [X] I have tested my changes locally and they are working as expected.
- [X] The code is formatted according to the project's coding guidelines and style.
- [X] Necessary documentation has been added or existing documentation has been updated.
- [X] Relevant unit tests have been written and included.
- [X] Relevant integration tests have been written and included.
- [X] The code has been reviewed to ensure its quality.
- [X] The code does not contain any issues flagged by SonarLint.
- [X] Default reviewers have been assigned to this pull request.
- [X] Assignees have been added if necessary.
- [X] Labels have been applied if necessary.
- [X] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

### Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-12-01 21:25 UTC, ibrahimdenizz commented
@agitrubard Conflict çözdüldü.

2023-12-02 13:11 UTC, agitrubard requested changes

2023-12-02 13:11 UTC, agitrubard commented on src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationResponseMapper.java
> +    AdminUserRegisterApplicationResponse map(AdminUserRegisterApplication source);
Listeleme endpointindeki gibi yapabilriiz burayı da

2023-12-02 13:11 UTC, agitrubard commented on src/test/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationListRequestBuilder.java
> +	}
Sanırım formatlamada bir problem var. Değişiklik yaptığımız sınıflarda formatlama yapabilir miyiz? 

Ek olarak commit atmadan önce otomatik formatlanmasını sağlayabiliriz;
https://www.jetbrains.com/guide/java/tutorials/reformatting-code/reformatting-before-commit/

2023-12-02 17:30 UTC, ibrahimdenizz commented on src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationResponseMapper.java
> +    AdminUserRegisterApplicationResponse map(AdminUserRegisterApplication source);
Kaldırıldı.

2023-12-02 17:31 UTC, ibrahimdenizz commented on src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
> +	}
Format ayarlarım default ayarlardan farklı olduğu için yanlış formatlama yapmış. Projedeki `*` importlarıyla beraber düzeltildi.

2023-12-03 08:38 UTC, agitrubard approved these changes

2023-12-03 08:38 UTC, merged