#246 | Add Filtering & Sorting Features to Get All Users Endpoint
afet-yonetim-sistemi/ays-be pull request #268
Opened 2023-12-08 19:12 UTC by AhmetAksunger

### Description

I have added the requested filtering and sorting features to the get all users endpoint.

### Related Issue

#246 

### Proposed Changes

Please provide a brief and descriptive title for your pull request, summarizing the changes or features introduced. It
should be in English and clearly indicate the purpose of the pull request. Optionally, you can provide a more detailed
description of what you have done.

- Branches should follow the below `Naming Conventions of Branchs` header in [README.md](https://github.com/afet-yonetim-sistemi/ays-be/edit/main/README.md) File

### Additional Information

If there's any additional information or context that the reviewers should know, please provide it here.

### Checklist

Please check the following before submitting your pull request:

- [x] I have tested my changes locally and they are working as expected.
- [x] The code is formatted according to the project's coding guidelines and style.
- [x] Necessary documentation has been added or existing documentation has been updated.
- [x] Relevant unit tests have been written and included.
- [x] Relevant integration tests have been written and included.
- [x] The code has been reviewed to ensure its quality.
- [x] The code does not contain any issues flagged by SonarLint.
- [x] Default reviewers have been assigned to this pull request.
- [x] Assignees have been added if necessary.
- [x] Labels have been applied if necessary.
- [x] If an issue is opened and this pull request is related to that issue, it should not be associated with any project
  board or milestone. However, if there is no issue, the pull request should be associated with the appropriate project
  board (BE Board, In Review column) and milestone to track the progress.

### Reviewers

The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

2023-12-10 11:05 UTC, agitrubard requested changes

2023-12-11 15:27 UTC, AhmetAksunger commented on src/main/java/com/ays/common/model/AysPhoneNumber.java
> +public class AysPhoneNumber implements AysPhoneNumberAccessor {
AysPhoneNumber sınıfını domain modele dönüştürdüm. Request sınıflarında kullanılması için AysPhoneNumberRequest sınıfnı oluşturdum. Testleri de o yapıya uygun olarak güncelledim.

Aynı zamanda AssignmentListRequest sınıfında bulunan PhoneNumber sınıfı yerine AysPhoneNumberFilterRequest sınıfını kullandım.

2023-12-11 15:27 UTC, AhmetAksunger commented on src/main/java/com/ays/common/model/AysPhoneNumberAccessor.java
> +}
Düzelttim

2023-12-11 15:27 UTC, AhmetAksunger commented on src/test/java/com/ays/common/model/AysPhoneNumberFilterRequestBuilder.java
> +    public AysPhoneNumberFilterRequestBuilder() {
Düzelttim

2023-12-13 09:58 UTC, agitrubard approved these changes

2023-12-13 17:28 UTC, anilhazar approved these changes

2023-12-13 19:42 UTC, merged