AYS-130 Invalidated Refresh Token Flow Fix
afet-yonetim-sistemi/ays-be pull request #284
Opened 2024-02-02 15:05 UTC by moaydogdu

Please provide a brief description of the changes made in this pull request.

### Checklist

Before submitting your pull request, ensure the following:

- [X] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [X] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [X] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [X] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes
      made in Postman.

- [X] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [X] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [X] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

- [X] **Jira Issue Transition:**
    - If this pull request is related to a Jira issue, ensure that the issue is moved to the "In Review" status on the
      Jira board.

2024-02-02 16:45 UTC, ibrahimdenizz requested changes

2024-02-02 16:45 UTC, ibrahimdenizz commented on src/test/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImplTest.java
> +        String mockRefreshToken = """
@moaydogdu @agitrubard AysRandomTestUtil class'ına generateToken diye bir method ekliyebilir miyiz? Her defasında static bir değer kullanmak yerine generateToken methodun'dan alabiliriz.

2024-02-02 16:45 UTC, ibrahimdenizz commented on src/test/java/com/ays/user/service/impl/UserAuthServiceImplTest.java
> +        String mockRefreshToken = """
@moaydogdu @agitrubard AysRandomTestUtil class'ına generateToken diye bir method ekliyebilir miyiz? Her defasında static bir değer kullanmak yerine generateToken methodun'dan alabiliriz.

2024-02-03 09:17 UTC, agitrubard commented on src/test/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImplTest.java
> +        String mockRefreshToken = """
Aslında burada bile isteye böyle bir şey kullanıyoruz, var olan token'ı bazen manuel olarak bozabiliyoruz fakat böyle bir şey yapılacaksa farklı bir issue'da bütün projeyi refactor etmek daha sağlıklı olur

2024-02-03 09:17 UTC, agitrubard commented on src/test/java/com/ays/user/service/impl/UserAuthServiceImplTest.java
> +        String mockRefreshToken = """
Aslında burada bile isteye böyle bir şey kullanıyoruz, var olan token'ı bazen manuel olarak bozabiliyoruz fakat böyle bir şey yapılacaksa farklı bir issue'da bütün projeyi refactor etmek daha sağlıklı olur

2024-02-03 09:18 UTC, agitrubard approved these changes

2024-02-03 09:30 UTC, ibrahimdenizz approved these changes

2024-02-03 12:15 UTC, merged