AYS-34 | Remove the Detailed Phone Number Validation from Filtering Requests
afet-yonetim-sistemi/ays-be pull request #286
Opened 2024-02-06 20:01 UTC by AhmetAksunger

I've removed the detailed phone number validation from **filtering** requests because it caused some unsolvable bugs.
Instead, there's much simpler validation for the `countryCode` and the `lineNumber` fields.

- `countryCode` : must be between 1 and 3 characters
- `lineNumber` : must be between 7 and 15 characters

Note: Just to make it clear, the validation mentioned above is only used for **filtering** requests.

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes
      made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

- [x] **Jira Issue Transition:**
    - If this pull request is related to a Jira issue, ensure that the issue is moved to the "In Review" status on the
      Jira board.

2024-02-07 14:17 UTC, agitrubard requested changes
Eline sağlık genel olarak okey, 1-2 yorumum oldu o kısmı hızlıca düzeltirsek sonrasında mergeleyebiliriz

2024-02-07 14:17 UTC, agitrubard commented on src/main/java/com/ays/common/model/dto/request/AysPhoneNumberFilterRequest.java
> +    @Size(min = 1, max = 3, message = "COUNTRY CODE MUST BE BETWEEN 1 AND 3 CHARACTERS")
Buraya mesaj yazmamıza ihtiyaç yok, sadece minimum ve maximum değerleri belirtmemiz yeterli

2024-02-07 14:17 UTC, agitrubard commented on src/main/java/com/ays/common/model/dto/request/AysPhoneNumberFilterRequest.java
> +    @Size(min = 7, max = 15, message = "LINE NUMBER MUST BE BETWEEN 7 AND 15 CHARACTERS")
Buraya mesaj yazmamıza ihtiyaç yok, sadece minimum ve maximum değerleri belirtmemiz yeterli

2024-02-07 14:17 UTC, agitrubard commented on src/main/java/com/ays/common/util/AysJsonUtil.java
> +    public static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
`GSON` objesini `private` yapabiliriz

2024-02-07 14:27 UTC, AhmetAksunger commented on src/main/java/com/ays/common/model/dto/request/AysPhoneNumberFilterRequest.java
> +    @Size(min = 1, max = 3, message = "COUNTRY CODE MUST BE BETWEEN 1 AND 3 CHARACTERS")
Kaldırdım

2024-02-07 14:28 UTC, AhmetAksunger commented on src/main/java/com/ays/common/util/AysJsonUtil.java
> +    public static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
Değiştirdim

2024-02-08 15:44 UTC, agitrubard approved these changes

2024-02-08 18:40 UTC, ibrahimdenizz approved these changes

2024-02-08 18:52 UTC, merged