AYS-142 | Forbid FirstName & LastName To Start With Special Characters
afet-yonetim-sistemi/ays-be pull request #288
Opened 2024-02-14 20:46 UTC by MenekseYuncu

We have revised Regex so that the firstname and the lastname cannot start with special characters.

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes
      made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

- [x] **Jira Issue Transition:**
    - If this pull request is related to a Jira issue, ensure that the issue is moved to the "In Review" status on the
      Jira board.

2024-02-15 03:51 UTC, agitrubard requested changes
Buradaki validasyonu sağlayan testler ekleyebilir miyiz?

2024-02-15 19:52 UTC, AhmetAksunger commented
> Buradaki validasyonu sağlayan testler ekleyebilir miyiz?

Ekledik, inceler misin?

2024-02-16 07:33 UTC, agitrubard approved these changes
@MenekseYuncu @AhmetAksunger Elinize sağlık, parameterized testler bayağı iyi olmuş 🚀

2024-02-16 07:33 UTC, agitrubard commented on src/main/java/com/ays/common/util/validation/NameValidator.java
>      static final Integer NAME_MAX_LENGTH = 255;
Eğer buradaki değişkenleri başka yerlerde kullanmıyorsak `private` access modifier kullanabilir miyiz

2024-02-16 21:27 UTC, anilhazar submitted a review, later dismissed

2024-02-17 07:32 UTC, merged