AYS-160 | Registering with Invalid Domain Extension Email
afet-yonetim-sistemi/ays-be pull request #290
Opened 2024-02-22 18:06 UTC by MenekseYuncu

Please provide a brief description of the changes made in this pull request.

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes
      made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

- [x] **Jira Issue Transition:**
    - If this pull request is related to a Jira issue, ensure that the issue is moved to the "In Review" status on the
      Jira board.

2024-02-25 23:08 UTC, moaydogdu submitted a review, later dismissed
LGTM!

2024-02-26 15:51 UTC, agitrubard requested changes

2024-02-26 15:51 UTC, agitrubard commented on src/main/java/org/ays/common/util/validation/EmailValidator.java
> +            "^[a-zA-Z0-9]+([._-][a-zA-Z0-9]+)*@[a-zA-Z0-9]+" + "([.-]?[a-zA-Z0-9]+)+\\.[a-zA-Z]{2,}$";
Burayla ilgili geliştirme yapacaktık, bu kısım tamamlandı mı?

2024-02-26 15:51 UTC, agitrubard commented on src/main/java/org/ays/common/util/validation/EmailValidator.java
> +
Buradaki fazladan boşluğu silebiliriz

2024-02-26 15:51 UTC, agitrubard commented on src/main/java/org/ays/common/util/validation/EmailValidator.java
> +
Buradaki fazladan boşluğu silebiliriz

2024-02-26 15:51 UTC, agitrubard commented on src/main/java/org/ays/common/util/validation/Email.java
> +
Buradaki fazladan boşluğu silebiliriz

2024-02-26 15:51 UTC, agitrubard commented on src/main/java/org/ays/common/util/validation/EmailValidator.java
> +        return email.matches(EMAIL_REGEX);
Aşağıdaki şekilde yazmamız yeterli olur. Zaten matches olmazsa false dönecek. Ek olarak burada email'in boş geldiği durumlarda regex ile karşılaştırmak yerine validasyondan geçmesini sağlamamız lazım çünkü öbür türlü `@NotBlank` anotasyonuyla çakışabilir.

```suggestion

        if (!String.hasText(email)) {
            return true;
        }

        return email.matches(EMAIL_REGEX);
```

2024-02-29 14:55 UTC, agitrubard approved these changes

2024-02-29 14:56 UTC, merged