AYS-121 | The Reason Field Is A Number Checked
afet-yonetim-sistemi/ays-be pull request #297
Opened 2024-03-25 19:12 UTC by MenekseYuncu

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes
      made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-03-25 19:23 UTC, agitrubard requested changes

2024-03-25 19:23 UTC, agitrubard commented on src/main/java/org/ays/common/util/validation/SpecialCharacterValidator.java
> +        if (value.matches("^\\d+$")) {
```suggestion
        boolean isIncludeOnlyDigits = value.matches("^\\d+$");
        if (isIncludeOnlyDigits) {
```

2024-03-26 05:41 UTC, AhmetAksunger approved these changes
Eline sağlık

2024-03-26 09:54 UTC, agitrubard approved these changes

2024-03-26 09:55 UTC, merged