AYS-254 | Add handler for NoResourceFoundException
afet-yonetim-sistemi/ays-be pull request #311
Opened 2024-05-28 14:59 UTC by egehanasal

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-05-29 04:59 UTC, agitrubard requested changes

2024-05-29 04:59 UTC, agitrubard commented on src/test/java/org/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java
> +        HttpMethod[] httpMethods = HttpMethod.values(); // Array containing all HTTP methods
```suggestion
        HttpMethod[] httpMethods = HttpMethod.values();
```

2024-05-29 10:05 UTC, agitrubard commented
@egehanasal Selamlar,
Pull request template'ini yapmadıklarımızı hatırlamak için kullanıyoruz.

Bu sebeple;
- Pull request açıklamasını **silmememiz**
- checklist üzerinden her madde için kontrolleri sağlayarak **yaptıysak tiklememiz**
- yapmadıysak **yaptıktan sonra tiklememiz**

gerekiyor.

Ek olarak diğer arkadaşları da reviewer olarak ekleyebiliriz.

2024-05-29 19:20 UTC, agitrubard approved these changes

2024-05-30 16:49 UTC, ybilgaz96 approved these changes

2024-05-30 19:15 UTC, merged