AYS-192 | User Detail Flow Has Been Created
afet-yonetim-sistemi/ays-be pull request #340
Opened 2024-07-08 12:02 UTC by egehanasal

### Checklist

Before submitting your pull request, ensure the following:

- [X] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [X] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [X] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [X] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [X] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [X] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [X] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-07-08 21:23 UTC, AbdullahCelikcode submitted a review, later dismissed

2024-07-09 10:34 UTC, agitrubard requested changes

2024-07-09 10:34 UTC, agitrubard commented on src/main/java/org/ays/auth/util/exception/AysUserNotExistException.java
> +public final class AysUserNotExistException extends AysNotExistException {
```suggestion
public final class AysUserNotExistByIdException extends AysNotExistException {
```

2024-07-09 10:34 UTC, agitrubard commented on src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
> +    }
Burada bütün fieldların varlığını kontrol edebilir miyiz?

2024-07-09 10:34 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysUserReadServiceImplTest.java
> +    void givenValidUserId_whenUserNotFoundById_thenThrowAysUserNotExistException() {
```suggestion
    void givenValidId_whenUserNotFoundById_thenThrowAysUserNotExistByIdException() {
```

2024-07-09 10:34 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysUserReadServiceImplTest.java
> +    void givenValidUserId_whenUserFoundById_thenReturnUser() {
```suggestion
    void givenValidId_whenUserFoundById_thenReturnUser() {
```

2024-07-09 11:19 UTC, egehanasal commented on src/main/java/org/ays/auth/util/exception/AysUserNotExistException.java
> +public final class AysUserNotExistException extends AysNotExistException {
değiştirdim

2024-07-09 11:19 UTC, egehanasal commented on src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
> +    }
güncelledim

2024-07-09 11:19 UTC, egehanasal commented on src/test/java/org/ays/auth/service/impl/AysUserReadServiceImplTest.java
> +    void givenValidUserId_whenUserNotFoundById_thenThrowAysUserNotExistException() {
değiştirdim

2024-07-09 11:20 UTC, agitrubard approved these changes

2024-07-10 09:32 UTC, MenekseYuncu approved these changes

2024-07-10 09:43 UTC, merged