AYS-224 | Emergency Evacuation Application Update
afet-yonetim-sistemi/ays-be pull request #341
Opened 2024-07-09 20:10 UTC by moaydogdu

### Checklist

Before submitting your pull request, ensure the following:

- [X] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [X] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [X] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [ ] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [ ] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [X] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [X] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-07-10 06:08 UTC, egehanasal commented
Pr şu an testler ve javadoc'lar bakımından eksik olduğundan dolayı bu pr'ı ready olmayacak şekilde güncelleyebilir miyiz?

2024-07-15 07:43 UTC, agitrubard requested changes

2024-07-15 07:43 UTC, agitrubard commented on src/main/java/org/ays/emergency_application/service/impl/EmergencyEvacuationApplicationServiceImpl.java
> +            EmergencyEvacuationApplicationRequestToDomainMapper.initialize();
@cengzayhn 
```suggestion
    private final AysIdentity identity;


    private final EmergencyEvacuationApplicationUpdateRequestToDomainMapper applicationRequestToDomainMapper =  EmergencyEvacuationApplicationUpdateRequestToDomainMapper.initialize();
```

2024-07-16 15:06 UTC, agitrubard requested changes

2024-07-16 15:06 UTC, agitrubard commented on src/main/java/org/ays/emergency_application/model/mapper/EmergencyEvacuationApplicationUpdateRequestToDomainMapper.java
> +    EmergencyEvacuationApplication map(EmergencyEvacuationApplicationRequest request);
```suggestion
```

2024-07-17 13:36 UTC, agitrubard approved these changes

2024-07-17 13:51 UTC, agitrubard approved these changes

2024-07-17 14:39 UTC, egehanasal approved these changes

2024-07-17 15:05 UTC, merged