AYS-345 | Unable to Delete Roles Not Associated with Institutions
afet-yonetim-sistemi/ays-be pull request #353
Opened 2024-07-29 20:44 UTC by MenekseYuncu

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-07-30 06:36 UTC, agitrubard requested changes

2024-07-30 06:36 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
> +                .thenReturn(UUID.randomUUID().toString());
Burada da yukarıda olduğu gibi yeni bir ID oluşturarak kullanabiliriz

2024-07-30 06:43 UTC, MenekseYuncu commented on src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
> +                .thenReturn(UUID.randomUUID().toString());
String mockId = "32657ecb-5172-401d-8b29-a8e4454e8243"; bunun gibi mi?

2024-07-30 06:47 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
> +                .thenReturn(UUID.randomUUID().toString());
Evet bu şekilde tanımlayabiliriz 👍🏼 fakat aynı ID olmamalı, çünkü testte farklı bir ID olacak diyoruz

2024-07-30 10:27 UTC, agitrubard requested changes

2024-07-30 10:27 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
> +                .thenReturn(mockRandomInstitutionId);
Bu bilgi dışarıdan gelmediği için `Given` alanına yazmamalıyız
```suggestion

        // When
        AysRole mockRole = new AysRoleBuilder()
                .withValidValues()
                .withId(mockId)
                .build();
        Mockito.when(roleReadPort.findById(Mockito.anyString()))
                .thenReturn(Optional.of(mockRole));

        Mockito.when(identity.getInstitutionId())
                .thenReturn("3b9dcab2-028f-4bb8-9c9b-23130d9579ae");
```

2024-07-30 16:52 UTC, agitrubard approved these changes

2024-07-31 22:55 UTC, egehanasal approved these changes

2024-08-01 06:43 UTC, merged