AYS-74 | User Delete Endpoint Has Been Created
afet-yonetim-sistemi/ays-be pull request #354
Opened 2024-07-30 18:33 UTC by MenekseYuncu

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-07-31 04:20 UTC, agitrubard requested changes

2024-07-31 04:20 UTC, agitrubard commented on src/test/java/org/ays/auth/controller/AysUserControllerTest.java
> +    }
Servis katmanındaki akışları burada test etmeyebiliriz, bu test yerine yetkiyle iligli bir test yazmamız daha iyi olabilir

2024-07-31 04:20 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysUserUpdateServiceImplTest.java
> +                .save(Mockito.any(AysUser.class));
```suggestion
        // Verify
        Mockito.verify(userReadPort, Mockito.times(1))
                .findById(Mockito.anyString());
                
        Mockito.verify(identity, Mockito.never())
                .getInstitutionId();

        Mockito.verify(userSavePort, Mockito.never())
                .save(Mockito.any(AysUser.class));
```

2024-08-01 06:44 UTC, agitrubard approved these changes

2024-08-01 07:29 UTC, egehanasal approved these changes

2024-08-01 07:42 UTC, merged