AYS-487 | Added exception handling for AysUserNotSuperAdminException
afet-yonetim-sistemi/ays-be pull request #381
Opened 2024-09-23 11:44 UTC by suhakopan

…class

### Checklist

Before submitting your pull request, ensure the following:

- [X] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [X] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [X] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [X] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [X] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [X] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [X] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-09-23 11:50 UTC, agitrubard requested changes

2024-09-23 11:50 UTC, agitrubard commented on src/main/java/org/ays/common/util/exception/handler/GlobalExceptionHandler.java
> +    }
Sadece exception'ın extend edildiği sınıfı değiştirmemiz yeterli, buraya ekstra bir kontrol eklememiz yanlış olmuş

2024-09-23 13:38 UTC, suhakopan commented on src/main/java/org/ays/common/util/exception/handler/GlobalExceptionHandler.java
> +    }
Haklısın şimdi gördüm kurulan yapıyı

2024-09-23 14:08 UTC, agitrubard requested changes
Yorumuma ek olarak end to end testlere bu case'i ekleyebilir miyiz? Gerçeklemek adına önemli olduğunu düşünüyorum

2024-09-23 14:08 UTC, agitrubard commented on src/main/java/org/ays/auth/util/exception/AysUserNotSuperAdminException.java
> +public final class AysUserNotSuperAdminException extends AccessDeniedException {
`AccessDeniedException` yerine `AysAuthException` hatasını yazmamız gerekiyor
```suggestion
public final class AysUserNotSuperAdminException extends AysAuthException {
```

2024-09-24 07:27 UTC, agitrubard requested changes
@suhakopan Test kısmıyla ilgili yazdığım bir yorum vardı. Onu da ekleyebilirsek sonrasında mergeleyebiliriz. Ek olarak testler çalışmıyor görünüyor. Bunun da düzeltilmesi gerekiyor. `mvn clean install` yapmadan mı geliştirmeyi ilerletiyoruz?

2024-09-24 10:02 UTC, suhakopan commented
> @suhakopan Test kısmıyla ilgili yazdığım bir yorum vardı. Onu da ekleyebilirsek sonrasında mergeleyebiliriz. Ek olarak testler çalışmıyor görünüyor. Bunun da düzeltilmesi gerekiyor. `mvn clean install` yapmadan mı geliştirmeyi ilerletiyoruz?

e2e testleri ile ilgili yorumu atlamışım kusura bakma, şimdi testlere bakarken gördüm AysAuthException'dan extend ediyoruz fakat bu exception handling'de 401 hata kodu dönüyoruz. Bizden istenen 403 dönülmesiydi

2024-09-26 20:33 UTC, agitrubard approved these changes

2024-09-28 10:23 UTC, merged