AYS-444 & AYS-510 | UUID has been added to the response and time bug has been fixed
afet-yonetim-sistemi/ays-be pull request #389
Opened 2024-10-12 12:51 UTC by alpemreelmas

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-10-13 12:47 UTC, MenekseYuncu approved these changes

2024-10-14 11:29 UTC, agitrubard requested changes
Javadoc'u da düzeltirsek bir sorun yok gibi görünüyor ✅

2024-10-14 11:29 UTC, agitrubard commented on src/main/java/org/ays/common/model/response/AysResponse.java
>       */
Javadoc değişmemiş gibi görünüyor

2024-10-15 17:43 UTC, agitrubard commented
@alpemreelmas Javadoc'u düzenleyebilir misin? Sonrasında mergeleyelim.

2024-10-16 14:54 UTC, alpemreelmas commented on src/main/java/org/ays/common/model/response/AysResponse.java
>       */
```suggestion
 /**
     * A success response with no content.
     */
```

Uygun mudur bu şekilde ?

2024-10-16 16:52 UTC, agitrubard commented on src/main/java/org/ays/common/model/response/AysResponse.java
>       */
Uygundur eline sağlık ✅

2024-10-16 16:58 UTC, agitrubard submitted a review, later dismissed

2024-10-17 07:47 UTC, merged