AYS-528 | The Validations Were Set Up In Accordance With The Standards.
afet-yonetim-sistemi/ays-be pull request #398
Opened 2024-11-09 11:47 UTC by MenekseYuncu

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-11-12 20:42 UTC, agitrubard requested changes

2024-11-12 20:42 UTC, agitrubard commented on src/test/java/org/ays/auth/controller/AysUserControllerTest.java
`@Name` kullandığımız başka yerler de var diye biliyorum. Kullanılan yerlerdeki `Controller` testlerine de ekleyebilir miyiz? Kaldırılması durumunda fark etmemiz daha kolay olur diye düşünüyorum.

2024-11-12 20:43 UTC, MenekseYuncu commented on src/test/java/org/ays/auth/controller/AysUserControllerTest.java
:) tamam

2024-11-14 09:19 UTC, agitrubard approved these changes

2024-11-14 11:12 UTC, egehanasal approved these changes

2024-11-14 11:20 UTC, merged