AYS-508 | Kiness Integration
afet-yonetim-sistemi/ays-be pull request #401
Opened 2024-11-19 18:37 UTC by alpemreelmas

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-11-20 13:09 UTC, agitrubard commented
@alpemreelmas bütün arkadaşları reviewer olarka ekleyebilir miyiz?

2024-11-20 13:12 UTC, agitrubard requested changes
Başlıkta yazan `Kiness` ifadesi yerine `Kinesis` yazabilir miyiz? Ek olarak DynamoDB entegrasyonunun da kaldırıldığını başlıkta belirtmemiz faydalı olur. Ya da DynamoDB entegrasyonunun Kinesis ile değiştirildiğini söyleyebiliriz.

2024-11-23 20:28 UTC, egehanasal approved these changes

2024-11-24 17:10 UTC, agitrubard approved these changes

2024-11-24 17:10 UTC, merged