fix: return 404 in case Admin Registration Status is not WAITING
afet-yonetim-sistemi/ays-be pull request #405
Opened 2024-11-24 16:29 UTC by idilalemdar

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [ ] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [ ] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [ ] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [ ] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [ ] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [ ] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-11-24 16:38 UTC, egehanasal requested changes
Basligi diger Pr'larda oldugu sekilde guncelleyebilir miyiz

2024-11-24 17:09 UTC, idilalemdar commented
> Basligi diger Pr'larda oldugu sekilde guncelleyebilir miyiz? Reviewerlara diger arkadaslarimizi ekleyip checklist'i de doldurabilirsek harika olur

PR başlığını güncelledim, branch adı içinde bundan sonra convention'a göre yaparım ama bunun için sanırım geçti artık. 
Bir de postman testine de tick attım ama docker compose up ile çalıştırdığımda sanki değişiklik yapılmamış gibi çalışıyor. Sadece database'i docker'da çalıştırıp app'in kendisini IDE üzerinden ayağa kaldırdığımdaysa beklendiği gibi çalışıyor. bu bahsettiğim durum beklenen bir durum mudur? cc: @egehanasal

2024-11-24 17:23 UTC, agitrubard commented
@idilalemdar Bu servis public bir servis aslında, burada bu değişikliği yapmamamız daha faydalı olabilir. Çünkü aksi durumda burada bütün hata mesajını gösteriyor olacağız. Bu durumda deneme şansını arttırmış oluyoruz. Bunun yerine bu değişikliği yapmadan 401 dönmesini sağlamamız daha faydalı olabilir. Issue açılırken benim gözümden kaçmış, QA ekibi de sanırım bu konuyu düşünmeden issue'yu oluşturmuş

2024-11-24 17:24 UTC, agitrubard requested changes
@idilalemdar Bu servis public bir servis aslında, burada bu değişikliği yapmamamız daha faydalı olabilir. Çünkü aksi durumda burada bütün hata mesajını gösteriyor olacağız. Bu durumda deneme şansını arttırmış oluyoruz. Bunun yerine bu değişikliği yapmadan 401 dönmesini sağlamamız daha faydalı olabilir. Issue açılırken benim gözümden kaçmış, QA ekibi de sanırım bu konuyu düşünmeden issue'yu oluşturmuş

2024-11-25 07:37 UTC, agitrubard commented
> tüh ya nasıl heyecanlıydım ilk pr'ım geçmek üzere diye :D

@idilalemdar emeğine sağlık 🥲 

Bu durum hata dokümanını oluşturmamızı sağladı. Süreci iyileştirmek adına dokümanı oluşturduk umuyoruz ki bu doküman ile birlikte bu tür hatalar yapmayacağız ✅ 

Pull requesti kapatıyorum bilginize.

2024-11-25 07:37 UTC, closed without merging