AYS-136 | SonarQube Integration
afet-yonetim-sistemi/ays-be pull request #406
Opened 2024-11-26 16:54 UTC by yusufkaya01

### Checklist

Before submitting your pull request, ensure the following:

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [x] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-11-27 17:30 UTC, agitrubard requested changes

2024-11-27 17:30 UTC, agitrubard commented on .github/workflows/test-environment-deployment.yml
> +        run: mvn --settings settings.xml -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=afet-yonetim-sistemi_ays-be_d0f7524c-aae5-4394-976c-0b286114d7ff -Dsonar.p
Bu adımları en sona eklemişiz, uygulama deploy olduktan sonra çalışacak. `"Starting Deployment to ECS..."` adımından önce çalışmalı 👀

2024-11-28 15:19 UTC, agitrubard approved these changes

2024-11-29 07:53 UTC, MenekseYuncu approved these changes

2024-11-29 08:24 UTC, alpemreelmas approved these changes

2024-11-29 13:38 UTC, agitrubard approved these changes

2024-11-29 13:39 UTC, merged