AYS-558 / Removing-accessTokenExpiresAt from Token Service
afet-yonetim-sistemi/ays-be pull request #408
Opened 2024-11-28 12:45 UTC by filizhelvaci

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [ ] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [ ] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [ ] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [ ] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [ ] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [ ] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-11-28 12:50 UTC, agitrubard requested changes
`accessTokenExpiresAt` alanını response'tan kaldırmak dönülmemesi için yeterli fakat bu değerin asıl oluşturulduğu yerleri de düzenlemek gerekiyor

2024-11-28 12:53 UTC, agitrubard commented
@filizhelvaci @yagmurbarank pull request başlığını standartlarımıza uygun olacak şekilde düzenleyebilir miyiz? Branch için de bir sonrakilerde dikkat edebilirsek süper olur 🙌🏼

2024-11-28 13:13 UTC, yagmurbarank commented on src/test/java/org/ays/auth/filter/AysBearerTokenAuthenticationFilterEndToEndTest.java
> -                            .isNotEmpty())
.andExpect(MockMvcResultMatchers.jsonPath("$.response.accessTokenExpiresAt").doesNotExist());
şu şekilde mi düzenlemeliyiz?

2024-11-28 14:37 UTC, agitrubard commented on src/test/java/org/ays/auth/filter/AysBearerTokenAuthenticationFilterEndToEndTest.java
> -                            .isNotEmpty())
`doesNotExist()` metodu var olup, boş olmasını kontrol ediyor diye biliyorum. Bunun yerine `doesNotHaveJsonPath()` metodunu kullanabiliriz diye düşünüyorum. Yine de bi javadoc'una bakıp karşılaştırmak ve ne işe yaradığını öğrenmek ve buna göre kullanmak en iyi çözümdür

2024-12-03 09:35 UTC, MenekseYuncu submitted a review, later dismissed

2024-12-05 14:58 UTC, egehanasal submitted a review, later dismissed

2024-12-06 21:33 UTC, agitrubard requested changes

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/AysEndToEndTest.java
> +}
```suggestion
}

```

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysTokenServiceImplTest.java
> +}
```suggestion
}

```

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/AysRestControllerTest.java
> +}
```suggestion
}

```

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/AysUnitTest.java
> +}
```suggestion
}

```

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
> +}
```suggestion
}

```

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/auth/filter/AysBearerTokenAuthenticationFilterEndToEndTest.java
> +}
```suggestion
}

```

2024-12-06 21:33 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysAuthServiceImplTest.java
> +}
```suggestion
}

```

2024-12-06 21:38 UTC, agitrubard requested changes

2024-12-06 21:38 UTC, agitrubard commented on src/main/java/org/ays/auth/model/AysToken.java
Bu sınıftaki Javadoc'u da güncelleyebilir miyiz?

2024-12-06 21:38 UTC, agitrubard commented on src/main/java/org/ays/auth/model/response/AysTokenResponse.java
Bu sınıftaki Javadoc'u da güncelleyebilir miyiz?

2024-12-10 10:54 UTC, agitrubard requested changes

2024-12-10 10:54 UTC, agitrubard commented on src/test/java/org/ays/AysEndToEndTest.java
> +
```suggestion
```

2024-12-11 08:01 UTC, agitrubard requested changes

2024-12-11 08:01 UTC, agitrubard commented on src/test/java/org/ays/AysEndToEndTest.java
> +
```suggestion
```

2024-12-11 17:49 UTC, agitrubard approved these changes

2024-12-13 08:04 UTC, MenekseYuncu approved these changes

2024-12-13 14:38 UTC, merged