AYS-582 | Restrict Non-Active Users from Sending Password Reset Requests
afet-yonetim-sistemi/ays-be pull request #415
Opened 2024-12-15 18:14 UTC by egehanasal

### Checklist

Before submitting your pull request, ensure the following:

- [X] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be/blob/main/CONTRIBUTING.md#branch-naming-conventions).

- [X] **Local Testing:**
    - I have tested my changes locally on Postman, and they are working as expected.

- [X] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by SonarLint.

- [X] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated, specifically detailing changes made in Postman.

- [X] **Testing:**
    - Relevant unit tests have been written and included.
    - Relevant integration tests have been written and included.

- [X] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [X] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-12-16 06:40 UTC, filizhelvaci approved these changes

2024-12-16 06:41 UTC, filizhelvaci approved these changes

2024-12-16 06:47 UTC, filizhelvaci approved these changes

2024-12-16 07:01 UTC, filizhelvaci approved these changes

2024-12-18 07:03 UTC, egehanasal commented on src/main/java/org/ays/auth/exception/AysUserNotActiveByStatusException.java
> +public final class AysUserNotActiveByStatusException extends AysAuthException {
cok mantikli, tamamdir oyle yapayim, normalde by status ve by id gibi exceptionlar olusturmusuz onu devam ettirmek istemistim

2024-12-18 10:35 UTC, agitrubard commented on src/main/java/org/ays/auth/exception/AysUserNotActiveByStatusException.java
> +public final class AysUserNotActiveByStatusException extends AysAuthException {
@egehanasal oradaki konu şu, mesela ID ile arama yapıp kullanıcıyı bulamadığımızda ID ile arattık bulamadık demek için By ID diye yazmıştık. Burada böyle bir durum tam olarak yok

2024-12-18 19:09 UTC, alpemreelmas approved these changes

2024-12-21 21:04 UTC, egehanasal commented on src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
> +        }
degisiklikleri yaptim 🙌

2024-12-23 08:25 UTC, agitrubard requested changes

2024-12-23 08:25 UTC, agitrubard commented on src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java
> +                .thenReturn(Optional.of(mockUser));
```suggestion
        // When
        AysUser mockUser = new AysUserBuilder()
                .withValidValues()
                .withEmailAddress(mockForgotPasswordRequest.getEmailAddress())
                .withStatus(AysUserStatus.PASSIVE)
                .build();
                
        Mockito.when(userReadPort.findByEmailAddress(Mockito.anyString()))
                .thenReturn(Optional.of(mockUser));
```

2024-12-23 08:29 UTC, egehanasal commented on src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java
> +                .thenReturn(Optional.of(mockUser));
done

2024-12-23 08:36 UTC, MenekseYuncu approved these changes

2024-12-23 08:55 UTC, merged