Refactor/59
afet-yonetim-sistemi/ays-be pull request #64
Opened 2023-05-30 18:18 UTC by ilkerCelimli

Issue 59 is done.

2023-06-01 18:45 UTC, skayikci approved these changes

2023-06-03 20:54 UTC, agitrubard requested changes

2023-06-03 20:54 UTC, agitrubard commented on src/main/java/com/ays/common/util/exception/model/AysError.java
> +        FORBIDDEN_ERROR("FORBIDDEN ERROR");
@ilkerCelimli, we can remove the header here and use the `AUTH_ERROR` header in the same way we use it in the application, even in the test side.

2023-06-03 20:54 UTC, agitrubard commented on src/main/java/com/ays/auth/security/CustomAuthenticationEntryPoint.java
> +}
@ilkerCelimli @Rapter1990 I reviewed the class you provided. I made some code modifications and you can review them as well.

2023-06-03 20:54 UTC, agitrubard commented on docker-compose.yml
> +
@ilkerCelimli Can we revert the change here? There shouldn't have been a need for such a modification specific to the development.

2023-06-03 20:54 UTC, agitrubard commented on .gitignore
> +.env
@ilkerCelimli Can we revert the change here? There shouldn't have been a need for such a modification specific to the development. Especially the changes made in the `application.yml` were preventing the application from being launched, so I had to remove them.

2023-06-04 08:40 UTC, agitrubard approved these changes

2023-06-04 08:41 UTC, merged