Feature/moving the tokentype field from the body section to the header section of the jwt
afet-yonetim-sistemi/ays-be pull request #69
Opened 2023-06-04 09:39 UTC by ilkerCelimli

TokenType değeri claims'den alınıp token headerine taşındı,

yeni token Access

`eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiI3OWIzMTZiZC01YzdiLTQ1NTctODNlOS1hOTZmYzNiNDMzMjkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODU4NzE0ODcsImV4cCI6MTY4NTg3ODY4Nywib3JnYW5pemF0aW9uSWQiOiI3N2VjZTI1Ni1iZjBlLTRiYmUtODAxZC0xNzMwODNmOGJkY2YiLCJ1c2VyTGFzdE5hbWUiOiJTaXN0ZW1pIiwidXNlclR5cGUiOiJBRE1JTiIsInVzZXJGaXJzdE5hbWUiOiJBZmV0IFnDtm5ldGltIiwidXNlcm5hbWUiOiJheXMtYWRtaW4ifQ.N4Yxu7bA49Qx7l0YH6tfUfdL90kI8IJcYGAVA2FUvohvKywCIOne9fQuLpNZRyWJnr4mqEp9VZIdjslGVdsFi0ncR2_rB6set2C86xFU_rPtHa5xcfwuj_LmByJoMFKi-agRgzQK4JjeZXmL4zDLERkRi7ZE8NCAZhLiEtXRSHhobBzMQGVkQkV1mPPWhGgYx6QTfRnw5kjT1H9DR4yNxXqpAgiG2qQhrHioQLjMrCaD7FDplOW3KnV3fQ2FzMRdY7QWp5575wiK23Tt-VBbherA_at5D01gzTDkng8YbfKiqcRhm4S8W-fV5RA6ho2p-vqkwlYSD4hf57QmggznBg`

Refresh
`
eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJkYTI3MDBkMi0zM2ExLTQ3NGEtYmZjYS05MjhjNDc1Y2NkMDkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODU4NzE0ODcsImV4cCI6MTY4NTk1Nzg4NywidXNlcm5hbWUiOiJheXMtYWRtaW4ifQ.mKR_UMb6kQHENfZmr8F50UhtW6KQ-TKLkm21ve0dFqqKlZk_8DUupiZmb8ABzyR8EIVRRjMEQVMglyRNtK-vVfgFQCTETWFjqc6Fw3N-ViefgTVM_rLwcu26hHTvmh7MQdS6X34csYTk9eaAH0FJPqbxhGmaAoFCZwyX1s_WWHUZy-iUbLIQUgkqM3MNt8VImLq8ORwXduyL1WU0FywhX1mQmCF-HhEapO-2RTsRT9otCeAZUQzITfHQpRJ45Q6ONNJqn2Volav9vKdttLlFq288KNYR9L2iz9U331rFfVnFxvFwxr_NCq65z1_WZxs7yMmWOarKOKynvX24fbI2eg`

jwt.io'dan kontrol edilebilir.

2023-06-04 17:08 UTC, agitrubard commented
@ilkerCelimli Pull request başlığına `Feature/` gibi bir prefix eklememize ihtiyacımız bulunmuyor, böyle bir standardımız da yok. Kaldırabilir miyiz?

2023-06-04 17:11 UTC, agitrubard requested changes
@ilkerCelimli Eline sağlık, buradaki geliştirmeler eksiksiz fakat bizim unit test için kullandığımız token'ları son hâliyle güncellememiz daha iyi olabilir. Onları da güncelledikten sonra mergeleyebiliriz.

2023-06-04 17:16 UTC, ilkerCelimli commented
@agitrubard  Postmandaki tokenleri mi diyorsunuz ?

2023-06-04 17:33 UTC, agitrubard commented
> @agitrubard Postmandaki tokenleri mi diyorsunuz ? Unit testler sorunsuz çalışıyor şuan,

Unit Test'lerde tanımlı olan token'lardan bahsediyorum. Testleri etkileyen bir durum değil fakat oradaki token'ların güncel olması gerektiğinden düzeltilmesi gerekiyor.

2023-06-04 17:33 UTC, agitrubard commented
> @ilkerCelimli Pull request başlığına `Feature/` gibi bir prefix eklememize ihtiyacımız bulunmuyor, böyle bir standardımız da yok. Kaldırabilir miyiz?

@ilkerCelimli Buradaki yorumuma uygun olarak pull request başlığını düzeltebilir miyiz?

2023-06-04 17:34 UTC, agitrubard commented
@ilkerCelimli Ek olarak issue Board üzerinde ilerletilmemiş, ilgili sütuna ilerletebilir miyiz?

2023-06-04 17:37 UTC, agitrubard requested changes

2023-06-04 17:37 UTC, agitrubard commented on src/main/java/com/ays/auth/service/impl/AysTokenServiceImpl.java
>                  .compact();
Commit etmeden önce kodu formatlayabilir miyiz? Boşluklar bu sınıf için doğru düzenlenmemiş görünüyor.

2023-06-04 17:47 UTC, ilkerCelimli commented
@agitrubard  Hallettim.

2023-06-04 18:32 UTC, agitrubard approved these changes

2023-06-06 19:17 UTC, ilkerCelimli commented
İntellij'den halledemedim nedense, ama sanırsam test tokenlerini değiştirdiğiniz için conflict çıkmış

2023-06-06 21:52 UTC, agitrubard commented
> İntellij'den halledemedim nedense, ama sanırsam test tokenlerini değiştirdiğiniz için conflict çıkmış 

@ilkerCelimli birlikte inceleyelim IDE üzerinden çözelim, olur mu?

2023-06-07 05:17 UTC, ilkerCelimli commented
> > İntellij'den halledemedim nedense, ama sanırsam test tokenlerini değiştirdiğiniz için conflict çıkmış 
> 
> @ilkerCelimli birlikte inceleyelim IDE üzerinden çözelim, olur mu? GitHub üzerinden çözünce hatalara sebebiyet verebiliyor. 

@agitrubard. Tabi müsait bir zamanınızda dcden mesaj atabilirseniz pair yapabiliriz

2023-06-07 19:43 UTC, Rapter1990 approved these changes
LGTM

2023-06-07 19:43 UTC, merged